#!/usr/bin/env bash
# Configures Nginx with a custom HTTP response header

# Update and install Nginx
apt-get -y update
apt-get -y install nginx

# Add the custom header using the hostname command directly
# This ensures the header is added even if $HOSTNAME is empty
sed -i "s/server_name _;/server_name _;\n\tadd_header X-Served-By \$(hostname);/" /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart