#!/usr/bin/env bash
# Installs and configures HAProxy on a new Ubuntu machine
# to distribute traffic to web-01 and web-02 using roundrobin

apt-get update
apt-get -y install haproxy

# Enable HAProxy
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Build a clean configuration file from scratch
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend alicia_frontend
    bind *:80
    mode http
    default_backend alicia_backend

backend alicia_backend
    mode http
    balance roundrobin
    server 7007-web-01 34.239.0.61:80 check
    server 7007-web-02 3.87.217.227:80 check
EOF

service haproxy restart