#!/usr/bin/env bash
# This script transfers a file from the client to the server using scp

# Check for correct number of arguments
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE=$1
IP=$2
USER=$3
KEY=$4

# Use scp to transfer the file to the home directory on the server
scp -o StrictHostKeyChecking=no -i "$KEY" "$FILE" "$USER@$IP:~/"


